const questions = [
  ["如果可以在宿舍里面做一件抽象的事，你会选择？",["在地上铺上野餐垫，完整复刻公园野餐的全套流程","购置几块大红布，把宿舍改造为复古老钱风私人电影放映厅","在两个上铺之间拴上牢固床单，搭建巨型宿舍吊床秋千","购入一个充气泳池，在宿舍体验泡澡"]],
  ["上课回宿舍，发现正在充电的充电宝已经烫得离谱，你会？",["怀疑产品质量，打算后续更换一个全新充电宝","存在安全隐患，拔掉插头静置降温","物尽其用，把发烫的充电宝拿来当冬日暖手宝","拿起滚烫的充电宝，去烫你的舍友"]],
  ["室友拔完牙之后脸部肿了一大圈，此时你会？",["找来冰块，帮室友冷敷消肿","建议室友服用止痛药缓解疼痛感","和室友上演《甄嬛传》宫斗大戏，互扇巴掌复刻“臣妾要告发熹贵妃私通”名场面","淡淡评价：现在你就是忧郁文艺消肿逼了"]],
  ["舍友正在和他的神人女友通电话，你会如何行动？",["尊重他人隐私，不去打扰二人通话","单方面不停骚扰舍友打电话","请求当他们的孩子，以后买东西带上你一份","在一旁发出怪异叫声，神与神的脑回路本就相通"]],
  ["军训期间，你遇到一位行为十分炸裂的豪哥，你会？",["刻意避开，他的神人等级我实在难以匹敌","觉得难以理解，拉着室友疯狂吐槽","利用宿舍道具偷偷模仿豪哥的名场面","视作灵魂知己，和他一起当全场显眼包"]],
  ["校园宿舍区突然闯进来一只小狗，你会？",["小狗很可爱，找一点狗粮投喂它","对小狗进行“波比波比波”魔性运镜","大喊：秦彻！家里进狼了，我好害怕！","对着大狗起哄：欸，大狗？叫叫叫"]],
  ["给你一次在全校出名的机会，你想以哪种方式爆火校园？",["和劣质水果摊主对线，化身校园正义斗士","cos 博士站在操场高喊：我要玩一辈子明日方舟","手握相机被众人簇拥，接受学弟学妹的夸赞","套上学校 IP 玩偶服，骑电动车狂飙校园被抓拍"]],
  ["你和朋友登上山顶拍夜景，朋友的尼康相机始终无法合焦，你会？",["化身技术佬，上手调试相机参数","站到镜头前方静静等候，做最好的模特","拿手电筒给自己补光，试图把夜景变成白天","幻想自己化作大鸟扇动翅膀，毕竟尼康只有打鸟才能对焦"]],
  ["朋友在山顶满怀愁绪，想赋诗抒怀，你该如何哄他？",["讲几个轻松笑话，逗朋友开心","抓拍朋友忧郁模样，保存专属表情包","开启超绝夹子音放声唱歌","大喊：你见过凌晨四点的洛杉矶吗？"]],
  ["寿司店里，你点了一份火炙柠檬金枪鱼寿司，你会？",["直接入口，安心享用这份美食","把金枪鱼、三文鱼等海鲜从夯到拉进行锐评","尝一口觉得无比美味，当场开启寿司直播带货","放弃金枪鱼，挑战直接啃柠檬，录制“轻松绷住”短视频"]],
  ["玩《我的世界》钓鱼时，幸运钓到一枚命名牌，你会？",["好好收集，留到后续再使用","给卫道士挂上专属名字","用来生成彩虹羊","将牛羊狗命名为朋友的名字，牵着到处游走"]],
  ["你亲手命名的彩虹羊不幸被雷劈死，你会？",["我根本不会去管这种无聊的事情","重新生成一只彩虹羊命名","为逝去的彩虹羊建一个小标记","修筑坟墓，摆满海泡菜并在墓前钓鱼"]],
  ["台风来袭，你被困在朋友宿舍楼无法外出，此时你会？",["借一把伞，想办法冒雨离开","权衡现实情况，选择留宿一晚","事已至此，激情拍摄雨景发朋友圈","换上艾伦沃克同款套装，冲进雨中豪情在天"]],
  ["食堂阿姨今天给你多打了一勺肉，你的第一反应是？",["礼貌说谢谢，然后正常吃饭","拍照发群里宣布今天运气不错","双手抱拳：这份恩情在下记住了","当场认阿姨为义母，并策划继承食堂大业"]],
  ["凌晨两点，宿舍走廊突然传来一声悠长的怪叫，你会？",["戴上耳塞继续睡觉","在群里问一句是谁还没睡","隔着门用同样的声音回应","立刻加入，完成一场跨楼层精神合唱"]],
  ["宿舍突然停电，整栋楼一片漆黑，你的第一反应是？",["打开手机手电筒，检查是不是跳闸","在宿舍群里询问什么时候恢复供电","举起手电筒打在下巴上，开始讲校园怪谈","冲到阳台高喊“全体目光向我看齐”，把整栋楼变成演唱会现场"]],
  ["老师点名时，把你的名字念错了，你会？",["下课后礼貌提醒老师","举手纠正，然后继续听课","顺势接受新名字，并用一天","从此建立新人格，要求全班配合世界观"]],
  ["午休时校园广播突然误放了一首动感神曲，全校都听见了，你会？",["觉得是操作失误，继续做自己的事","和朋友笑一下，猜是谁不小心放的","走到走廊卡着广播节奏来一段即兴舞蹈","立刻冲到操场领舞，并示意教学楼里的同学隔空为你伴奏"]],
  ["朋友说“等一下”，结果半小时都没回来，你会？",["发消息问他还需要多久","先去做自己的事情","宣布自己已在等待中修炼成石像","为失踪的朋友编写完整都市传说"]],
  ["拍毕业照时，摄影师说“最后一张，大家自由发挥”，你会？",["正常微笑，看向镜头完成合照","和身边同学一起比个夸张的手势","突然背对镜头仰望天空，给毕业照留下一位神秘背影","身穿黑衣站到队伍正中，完成空气投篮后定格成狮身人面像姿势"]]
];

const profiles = [
  {max:28,name:"入机",code:"HUMAN",quote:"精神牢牢扎根现实大地，现实中唯一的正常人。",tags:["现实主义选手","脚踏实地","务实本位"],rarity:"26.5%",color:"#e7b94c",desc:"你是标准的入机，精神世界牢牢绑定现实。大部分时候你的思绪不会乱飞，看待事物习惯优先看实际用处，很少沉浸虚无缥缈的脑洞与氛围感。面对荒诞抽象的梗，你可以看懂，但总觉得周边都是神经病吧！我去你们干嘛呢？",tip:"偶尔允许思绪飘一会儿，你的精神世界也可以体验一把脱离地面的快乐。",kind:"reader"},
  {max:48,name:"伪人",code:"FAKER",quote:"表面正常人类，私下其实是 faker。",tags:["伪人外壳","后室的实体","半现实半幻想"],rarity:"34.0%",color:"#86b9aa",desc:"外表完全是正常人，社交、做事、过日子都可以完美适配现实规则，别人很难看出异样。但只有你自己知道，分享给朋友的视频充满了各种变异奶龙，时不时不小心说出一个热梗。该干活的时候依旧可以回归现实，属于「可收可放」的类型。",tip:"你的抽象雷达已经启动，只是仍然披着一件合身的人类外壳。",kind:"masked"},
  {max:68,name:"老绷家",code:"STIFF",quote:"其实你知道绷不住了，只是在硬撑罢了。",tags:["神人初见端倪","硬撑大师","热梗雷达"],rarity:"24.2%",color:"#ef795f",desc:"此刻你已经了解了网上 70% 的梗，逐渐修炼至至臻之境。可惜在你的世界里，搞笑仿佛被视作违法事件，所以只能苦苦修炼绷绷神功，把世界当成一个巨大的不要笑挑战。",tip:"脸上风平浪静，心里早已举办三轮抽象艺术节。",kind:"laugher"},
  {max:87,name:"赛亚级嘉豪",code:"S-J",quote:"吾乃承天命之人。",tags:["赛亚级嘉豪","托马斯回旋","狮身人面像"],rarity:"14.5%",color:"#3f4946",scene:"老师：这道题的答案是 1/2。\n我：写 0.5 可以吗？\n老师：可以。\n我（打个响指）：Nice！",desc:"嘉豪等级已经解锁！你可以是长发男、短发女、不知火舞、佐助，也可以身着黑衣在校园里淡定自如地做空气投篮。你拥有极强的氛围感感知，愿意为精神体验牺牲一部分现实逻辑。可是别人不知道的是，神通常是别人无法理解的。",tip:"你的精神能量已经很强，偶尔收起招式并不会影响嘉豪的身份，反而能让下一次出场更有冲击力。",kind:"jiahao"},
  {max:100,name:"神本无相",code:"GOD",quote:"神么？已经好久没有人这么称呼我了。",tags:["神本无相","中国人能飞","鬼脑连接"],rarity:"0.8%",color:"#596b98",desc:"恭喜解锁隐藏档位「神本无相」！你已经可以让世间所有的梗融会贯通，梗指南、梗百科见你都流汗。日常行为完全无法预测，与别人沟通全靠鬼脑连接。你已非凡人可匹敌，并且神人之程度可以迅速进行广泛传播。",tip:"神人也要记得照顾现实生活，不要让精神完全吞噬肉体喵。",kind:"thinker"}
];

const screens=["welcome","quiz","loading","result"];
let current=0, answers=[], dimensions={imagination:0,drift:0,sense:0,reality:0}, finalData=null;
const $=id=>document.getElementById(id);
function show(id){screens.forEach(x=>$(x).classList.toggle("active",x===id));window.scrollTo(0,0)}
function renderQuestion(){const q=questions[current];$("count").textContent=`${String(current+1).padStart(2,"0")} / 20`;$("questionNo").textContent=`QUESTION ${String(current+1).padStart(2,"0")}`;$("progressBar").style.width=`${(current+1)/20*100}%`;$("questionText").textContent=q[0];$("options").innerHTML=q[1].map((x,i)=>`<button class="option" data-index="${i}"><b>${"ABCD"[i]}</b><span>${x}</span></button>`).join("");document.querySelectorAll(".option").forEach(el=>el.addEventListener("click",choose));}
function choose(e){const btn=e.currentTarget,i=+btn.dataset.index;if(document.querySelector(".option.selected"))return;btn.classList.add("selected");answers.push(i);const w=[0,1,2,3][i];dimensions.imagination+=w*(current%3===0?1.2:1);dimensions.drift+=w*(current%3===1?1.2:1);dimensions.sense+=w*(current%3===2?1.2:1);dimensions.reality+=(3-w);setTimeout(()=>{$("questionWrap").classList.add("out");setTimeout(()=>{current++;if(current<questions.length){renderQuestion();$("questionWrap").classList.remove("out")}else finish()},220)},230)}
function finish(){show("loading");const texts=["连接精神脑回路","扫描抽象波段","校准现实落地感","人格档案生成中"];let n=0;const timer=setInterval(()=>$("loadingText").textContent=texts[++n%texts.length],700);setTimeout(()=>{clearInterval(timer);calculate();show("result")},3300)}
function calculate(){const raw=answers.reduce((a,b)=>a+b,0);const score=Math.round(10+(raw/(questions.length*3))*90);const maxDim=questions.reduce((a,_,i)=>a+(i%3===0?3.6:3),0);const vals={imagination:Math.round(8+dimensions.imagination/maxDim*92),drift:Math.round(5+dimensions.drift/maxDim*95),sense:Math.round(12+dimensions.sense/maxDim*88),reality:Math.round(100-dimensions.drift/maxDim*92)};const profile=profiles.find(p=>score<=p.max);finalData={score,vals,profile};renderResult()}
function renderResult(){const {score,vals,profile:p}=finalData;$("resultName").textContent=p.name;$("resultCode").textContent=p.code;$("resultQuote").textContent=p.quote;$("scene").textContent=p.scene||"";$("description").textContent=p.desc;$("tip").textContent="小提示："+p.tip;$("tags").innerHTML=p.tags.map(t=>`<span># ${t}</span>`).join("");$("rarity").textContent=`和你同类型的人占全网 ${p.rarity}`;$("resultCharacter").dataset.kind=p.kind;document.documentElement.style.setProperty("--profile",p.color);document.querySelector(".avatar-body").style.background=p.color;animateScore(score);drawRadar(vals,p.color)}
function animateScore(target){let n=0;const t=setInterval(()=>{n+=Math.max(1,Math.ceil((target-n)/8));if(n>=target){n=target;clearInterval(t)}$("scoreNumber").textContent=n},30)}
function drawRadar(v,color){const c=$("radar"),ctx=c.getContext("2d"),cx=260,cy=205,r=145,vals=[v.imagination,v.drift,v.sense,v.reality],labels=["想象力","游离度","感知力","落地感"];ctx.clearRect(0,0,c.width,c.height);ctx.font="13px Microsoft YaHei";ctx.textAlign="center";for(let ring=1;ring<=4;ring++){ctx.beginPath();for(let i=0;i<4;i++){const a=-Math.PI/2+i*Math.PI/2,x=cx+Math.cos(a)*r*ring/4,y=cy+Math.sin(a)*r*ring/4;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.strokeStyle="rgba(37,35,31,.14)";ctx.stroke()}for(let i=0;i<4;i++){const a=-Math.PI/2+i*Math.PI/2;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r);ctx.stroke();const lx=cx+Math.cos(a)*(r+36),ly=cy+Math.sin(a)*(r+30);ctx.fillStyle="#25231f";ctx.fillText(`${labels[i]} ${vals[i]}`,lx,ly+4)}ctx.beginPath();vals.forEach((n,i)=>{const a=-Math.PI/2+i*Math.PI/2,x=cx+Math.cos(a)*r*n/100,y=cy+Math.sin(a)*r*n/100;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fillStyle=color+"55";ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=3;ctx.stroke();vals.forEach((n,i)=>{const a=-Math.PI/2+i*Math.PI/2;ctx.beginPath();ctx.arc(cx+Math.cos(a)*r*n/100,cy+Math.sin(a)*r*n/100,4,0,Math.PI*2);ctx.fillStyle=color;ctx.fill()})}
function reset(){current=0;answers=[];dimensions={imagination:0,drift:0,sense:0,reality:0};renderQuestion();show("welcome")}
function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800)}
function drawPosterAvatar(x,p){x.save();x.translate(775,170);x.fillStyle=p.color+"33";x.beginPath();x.arc(110,150,145,0,Math.PI*2);x.fill();x.strokeStyle="#25231f";x.lineWidth=5;x.fillStyle="#f0b79e";x.beginPath();x.roundRect(65,48,90,102,38);x.fill();x.stroke();x.fillStyle=p.kind==="jiahao"?"#1f2222":p.color;x.beginPath();x.roundRect(35,135,150,185,30);x.fill();x.stroke();x.fillStyle="#25231f";x.beginPath();if(p.kind==="thinker"){x.strokeStyle="#e7b94c";x.lineWidth=6;x.ellipse(110,32,72,18,0,0,Math.PI*2);x.stroke()}else if(p.kind==="reader"){x.fillStyle="#fff7dc";x.fillRect(40,205,140,82);x.strokeRect(40,205,140,82);x.fillStyle="#25231f";x.font="20px serif";x.fillText("现实指南",70,250)}else if(p.kind==="masked"){x.fillStyle="#fffdf8";x.beginPath();x.ellipse(135,99,32,48,0,0,Math.PI*2);x.fill();x.stroke();x.font="24px serif";x.fillStyle="#25231f";x.fillText("◉",126,95);x.fillText("◡",125,125)}else if(p.kind==="laugher"){x.font="25px serif";x.fillText("⌒  ⌒",76,105);x.fillText("﹏",100,132)}else{x.fillStyle="white";x.font="bold 28px sans-serif";x.fillText("J",101,235)}x.restore()}
function downloadPoster(){if(!finalData)return;const {score,profile:p}=finalData,c=document.createElement("canvas");c.width=1080;c.height=1440;const x=c.getContext("2d");x.fillStyle="#f6f1e8";x.fillRect(0,0,c.width,c.height);x.fillStyle=p.color;x.fillRect(0,0,34,c.height);x.fillStyle="#25231f";x.font="bold 28px Microsoft YaHei";x.fillText("神人·抽象浓度测试",80,95);x.font="24px Microsoft YaHei";x.fillStyle="#706b63";x.fillText("我的抽象人格",80,230);x.font="bold 110px serif";x.fillStyle="#25231f";x.fillText(p.name,80,360);x.font="22px Microsoft YaHei";x.fillStyle=p.color;x.fillText(p.code,85,410);drawPosterAvatar(x,p);x.font="26px Microsoft YaHei";x.fillStyle="#706b63";x.fillText("神的浓度",80,535);x.font="bold 170px serif";x.fillStyle=p.color;x.fillText(score+"%",80,700);x.font="32px serif";x.fillStyle="#25231f";wrapText(x,p.quote,80,790,870,52);x.strokeStyle="rgba(37,35,31,.2)";x.beginPath();x.moveTo(80,905);x.lineTo(1000,905);x.stroke();x.font="bold 26px Microsoft YaHei";x.fillText("人格解读",80,970);x.font="24px serif";x.fillStyle="#514d47";wrapText(x,p.desc,80,1020,650,42);x.font="20px Microsoft YaHei";x.fillStyle=p.color;x.fillText(p.tags.map(t=>"#"+t).join("  "),80,1245);const box=document.createElement("div");box.style.cssText="position:fixed;left:-9999px;width:180px;height:180px";document.body.appendChild(box);new QRCode(box,{text:getShareUrl(),width:180,height:180,colorDark:"#25231f",colorLight:"#fffdf8",correctLevel:QRCode.CorrectLevel.M});setTimeout(()=>{const qr=box.querySelector("canvas,img");if(qr)x.drawImage(qr,820,1170,170,170);x.fillStyle="#25231f";x.font="bold 22px Microsoft YaHei";x.fillText("扫码测测你的神人等级",80,1340);box.remove();const a=document.createElement("a");a.download=`我的抽象人格-${p.name}.png`;a.href=c.toDataURL("image/png");a.click();toast("结果海报已生成")},100)}
function wrapText(ctx,text,x,y,max,line){let s="",yy=y;for(const ch of text){if(ctx.measureText(s+ch).width>max){ctx.fillText(s,x,yy);s=ch;yy+=line}else s+=ch}ctx.fillText(s,x,yy)}
function getShareUrl(){return location.protocol==="file:"?location.href:location.origin+location.pathname}
function renderShareQr(){const box=$("shareQr");box.innerHTML="";new QRCode(box,{text:getShareUrl(),width:160,height:160,colorDark:"#25231f",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.M});$("shareUrl").textContent=getShareUrl()}
document.querySelectorAll(".character").forEach(ch=>ch.addEventListener("click",()=>{document.querySelectorAll(".character").forEach(x=>x.classList.remove("focused"));ch.classList.add("focused");$("characterHint").textContent=ch.dataset.hint;setTimeout(()=>ch.classList.remove("focused"),1600)}));
$("heroArt")?.addEventListener("mousemove",()=>{});const art=document.querySelector(".hero-art");art.addEventListener("mousemove",e=>{const r=art.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;document.querySelectorAll(".portal").forEach((p,i)=>p.style.transform=`translate(${x*(i?10:18)}px,${y*(i?10:18)}px)`)});art.addEventListener("mouseleave",()=>document.querySelectorAll(".portal").forEach(p=>p.style.transform=""));
$("startBtn").onclick=()=>{renderQuestion();show("quiz")};$("quitBtn").onclick=reset;$("restartBtn").onclick=reset;$("posterBtn").onclick=downloadPoster;$("shareBtn").onclick=()=>{renderShareQr();$("shareModal").classList.add("open");$("shareModal").setAttribute("aria-hidden","false")};$("closeModal").onclick=()=>{$("shareModal").classList.remove("open");$("shareModal").setAttribute("aria-hidden","true")};$("copyBtn").onclick=async()=>{try{await navigator.clipboard.writeText(getShareUrl());toast("测试链接已复制");$("shareModal").classList.remove("open")}catch{toast("请复制浏览器地址分享")}};
